PKG_NAME := pypi-huggingface_hub
URL = https://files.pythonhosted.org/packages/ff/21/64d82073095c0b60ad366ef9349599d49efe68979e9e01517df6bea7ceb3/huggingface_hub-0.13.2.tar.gz
ARCHIVES = 

include ../common/Makefile.common
